version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

  dispatcher:
    build: ./dispatcher
    ports:
      - "8084:8084"
    environment:
      BOT_USERNAME: ${BOT_USERNAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_WEBHOOK_URI: ${BOT_WEBHOOK_URI}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    depends_on:
      - rabbitmq
    networks:
      - app-network

  node:
    build: ./node
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge